set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)


#get_cmake_property(_variableNames VARIABLES)
#list (SORT _variableNames)
#foreach (_variableName ${_variableNames})
#    message(STATUS "${_variableName}=${${_variableName}}")
#endforeach()

set(AVOCADO_PROJECT_ROOT "${VCPKG_ROOT_DIR}\\..")
set(SYSTEM_HOOK_ROOT "${AVOCADO_PROJECT_ROOT}\\system-hook")
message(STATUS "AVOCADO_PROJECT_ROOT=${AVOCADO_PROJECT_ROOT}")
message(STATUS "PORT=${PORT}")
if(PORT MATCHES "^boost-.*")
	message(STATUS "MATCHED PORT=${PORT}")
	set(VCPKG_LINKER_FLAGS_DEBUG "${SYSTEM_HOOK_ROOT}\\SysHook\\SysHook\\x64\\Debug\\sh_hook_new.obj ${SYSTEM_HOOK_ROOT}\\SysHook\\x64\\Debug\\SysHook.lib")
	set(VCPKG_LINKER_FLAGS_RELEASE "${SYSTEM_HOOK_ROOT}\\SysHook\\SysHook\\x64\\Release\\sh_hook_new.obj ${SYSTEM_HOOK_ROOT}\\SysHook\\x64\\Release\\SysHook.lib")
endif()
